"""Swedish function words.

Used by the retrieval gate only, to recognise a query that carries no clinical
content at all. It is not a search stopword list -- PostgreSQL's `swedish` text
search configuration does its own stop-word removal inside the full-text index,
and this list has no effect there.

Scope, deliberately narrow: articles, conjunctions, prepositions, pronouns,
auxiliaries and a few adverbs of degree. Anything that could carry clinical
meaning is left out, because a false entry here silently blocks a real query.
`akut`, `kronisk`, `svår`, `höger`, `vänster`, `övre`, `nedre` and the like are
therefore absent on purpose -- they are content words in a clinical phrase, not
function words.

Derived from the common core of Swedish function-word lists (the same set
PostgreSQL's snowball `swedish` configuration and NLTK's Swedish stopwords
agree on), trimmed by hand against that rule.
"""

from __future__ import annotations

SWEDISH_STOPWORDS: frozenset[str] = frozenset(
    {
        # articles and determiners
        "en",
        "ett",
        "den",
        "det",
        "de",
        "dem",
        "denna",
        "detta",
        "dessa",
        "någon",
        "något",
        "några",
        "ingen",
        "inget",
        "inga",
        "all",
        "alla",
        "allt",
        "varje",
        "sådan",
        "sådant",
        "sådana",
        "samma",
        "andra",
        "annan",
        "annat",
        # conjunctions
        "och",
        "eller",
        "men",
        "samt",
        "att",
        "som",
        "om",
        "för",
        "fast",
        "eftersom",
        "medan",
        "utan",
        "både",
        "antingen",
        "varken",
        # prepositions
        "av",
        "i",
        "på",
        "till",
        "från",
        "med",
        "vid",
        "under",
        "över",
        "efter",
        "före",
        "mellan",
        "genom",
        "mot",
        "hos",
        "åt",
        "per",
        "kring",
        "bland",
        "inom",
        "utanför",
        "innanför",
        "ovan",
        "nedan",
        # pronouns
        "jag",
        "du",
        "han",
        "hon",
        "hen",
        "vi",
        "ni",
        "man",
        "mig",
        "dig",
        "honom",
        "henne",
        "oss",
        "er",
        "sig",
        "min",
        "mitt",
        "mina",
        "din",
        "ditt",
        "dina",
        "hans",
        "hennes",
        "vår",
        "vårt",
        "våra",
        "era",
        "deras",
        "sin",
        "sitt",
        "sina",
        "vem",
        "vad",
        "vilken",
        "vilket",
        "vilka",
        # auxiliaries and very common verbs
        "är",
        "var",
        "vara",
        "varit",
        "har",
        "hade",
        "ha",
        "haft",
        "blir",
        "blev",
        "bli",
        "blivit",
        "kan",
        "kunde",
        "kunna",
        "ska",
        "skall",
        "skulle",
        "vill",
        "ville",
        "får",
        "fick",
        "få",
        "måste",
        "bör",
        "borde",
        "gör",
        "gjorde",
        "göra",
        # adverbs and particles with no clinical content
        "inte",
        "icke",
        "ej",
        "ju",
        "nu",
        "då",
        "här",
        "där",
        "när",
        "hur",
        "så",
        "mycket",
        "mer",
        "mest",
        "mindre",
        "minst",
        "bara",
        "endast",
        "också",
        "även",
        "redan",
        "ännu",
        "alltid",
        "aldrig",
        "ofta",
        "ibland",
        "kanske",
        "helt",
        "ganska",
        "väldigt",
        "lite",
        "litet",
        "flera",
        "sedan",
        "innan",
        "därefter",
        "dessutom",
        "således",
        "alltså",
    }
)
